### ISSUE TITLE
新增功能：快递箱 用于替代 Mailbox 插件

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/nyaautils#10]
原插件 https://dev.bukkit.org/bukkit-plugins/mailbox-plugin/ 已经年久失修。主要存在问题：

* 对错误处理很差，例如存储的快递箱被改变为其他方块，存储时会直接报错
* 不支持 NBT，如果对方的快递箱满了或者其他任何错误，退回的物品会丢失属性（这个相当要命
* 不支持多语言
* 不支持 UUID

但是数据库中已经有不少玩家的快递箱，所以需要先做一个导入先前插件数据库的功能（只需要存在一个版本中即可，之后的版本可以移除这个功能）

配置文件

```
mail:
  hand: 10 # per hand item(s) mail cost
  chest: 1000 # per chest item(s) mail cost
  cooldown: 20 # cooldown ticks between next mail
  timeout: 200 # timeout ticks to accept/refuse mail
```

玩家快递箱的存储，使用文本数据库即可（如果担心数据量大了性能问题就继续用 SQLite）。需要支持 UUID。当玩家上线时检查数据库中 UUID 对应的玩家名是否需要更新，如果要更新则更新相关条目，正好可以作为发送快递时 UUID <-> 玩家名的缓存。

玩家命令

* `/nu mailbox create` 执行后右键点击箱子以设置邮箱
* `/nu mailbox remove` 移除自己的邮箱
* `/nu mailbox info` 查看自己邮箱信息(位置、内含物品数量等)
* `/nu mailbox send [player]` 或者 `/nu msend [player]` 将手中的物品发送到指定玩家的邮箱
* `/nu mailbox sendchest [player]` 或者 `/nu msendchest [player]` 然后右键点击箱子，将箱子中的物品发送到指定玩家的邮箱
* ~~`/nu mailbox [accept|refuse]` 或者 `/nu mailbox [ac|re]` 接受或拒收邮件~~ 此功能暂时搁置

管理员命令

* `/nu mailbox create [player]` 创建相应玩家的邮箱
* `/nu mailbox remove [player]` 移除相应玩家的邮箱
* `/nu mailbox info [player]` 查看相应玩家邮箱的信息

几种情况：

1. 发送邮件时检查目标玩家是否设置了有效的邮箱，没有邮箱、邮箱不是箱子方块或者邮箱空间不够则拒绝发送邮件
2. ~~发送邮件后，如对方玩家在线则提示接收，如果超时或者玩家不在线，则默认接收，物品放入邮箱里~~
3. 每个玩家只能创建一个邮箱，如果已经有了邮箱，再次创建会显示邮箱信息，要求先移除之前的邮箱才能再创建

权限组

* `nu.mailbox` - 对应所有玩家命令，默认为玩家
* `nu.mailboxadmin` - 对应管理员命令，默认为 op
