### ISSUE TITLE
新增功能：计时器

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/nyaautils#13]
此功能需要 hook worldedit

配置文件 `timers.yml` 示例

```
timers:
  icetrack:
    checkpoint:
      '0':
        pos1: (world, 120, 65, -230)
        pos2: (world, 150, 70, -230)
      '1':
        pos1: (...)
        pos2: (...)
      '2':
        pos1: (...)
        pos2: (...)
    broadcast: [true/false]
```

管理员命令：

* `/nu timer create [timer name]` 创建名为 `timer name` 的计时器，例如 `/nu timer create icetrack`
* 使用 WE 选择一块方形区域
* `/nu timer addcheckpoint [timer name]` 给 `timer name` 添加一个检查点。如果区域重复则不添加到配置，提示重复
* `/nu timer togglebroadcast [timer name]` 设置 `timer name` 的广播行为，值为 `true` 时广播信息到全服务器，`false` 时仅广播给对应玩家。默认是 `true`
* `/nu timer info [timer name]` 查看 `timer name` 的信息
* `/nu timer remove [timer name]` 移除 `timer name`

`checkpoint 0` 将作为起点，最后一个 checkpoint 作为终点。每个 timer 必须至少有 2 个 checkpoint 否则不生效。玩家通过第一个 checkpoint 时开始计时（记录 time stamp），每通过一个 checkpoint 时记录一次 time stamp 并广播该玩家上一段的耗时，通过最后一个 checkpoint 时广播计时数据，例如：

```
Player (id)'s timer at (timer name):
  - time to checkpoint 1 [ 1 min 30s ]
  - time to checkpoint 2 [ 2 min 15s ]
  - time total [ 3min 45s ]
```

插件后台不做任何持续计时的计算，仅当玩家通过起点时设置该玩家的计时为 active 并记录此时的 unix timestamp，之后按顺序通过每一个 checkpoint 记录通过时的 timestamp。计时状态为 active 但不按照顺序通过时通知玩家计时无效（此消息忽略计时区的广播设定，永远只发给相应玩家），非 active 时不检查此玩家的计时也不广播任何消息。如果玩家的计时状态为 active 但重复通过了起始 checkpoint，则每次通过即重置计时。同时，不同的计时区分别记录，互不影响。

目前所有的计时均不需要持久化，后台也不需要有任何持续性的计算所以计时数据可以直接存在内存里。reload 或者重启即清空所有数据和状态。该功能主要用于制作活动场地等。
