### ISSUE TITLE
新功能：Kit

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/nyaautils#17]
用于替代 SignShop 的 kit 功能，但是可以轻量得多。

配置文件 `kit.yml`

```
kits:
  'kitname':
    content: (data of items)
    players:
    - list of uuids
```

命令

* `/nu kit [create|remove] [kitname]` - 创建/更新/删除 kit，例如 `/nu kit create examplekit` 然后右键装有物品的箱子来保存或更新该 kit。权限 `nu.kit.admin` 默认为 op
* `/nu kit give [kitname] [player]` - 将 `kitname` 给予 `player`。可以在命令方块或 rpgitem 中使用。对应玩家的 UUID 将被记录到配置文件相应 kit 中，之后即无法再次获得该 kit。权限 `nu.kit.give` 默认为 op
* `/nu kit reset [kitname] [player]` - 重置 `player` 的 `kitname` 获取状态，执行后，该玩家即可再次通过合理途径获得一次该 kit。权限 `nu.kit.reset` 默认为 op
