### ISSUE TITLE
新功能：Particles

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/NyaaUtils#31]
加进来的原因是 ElytraParticles 的作者不修 bug................................................

配置文件 `config.yml`

```
# enable or disable certain type/particle globally
particles:
  type:
    player: true
    elytra: true
    others: true  # projectiles by this player, arrows, snowballs, etc...
  enabled:
  - happyVillager
  - (list of particles)...
  limits:
    player:
      set: 2
      amount: 3
      freq: 20
      duration: 10  # limits for player particles: maximum 2 types of particles combined, no more than 3 per spawn, more than 20 ticks per spawn, lasts for 10 ticks the longest
    elytra:
      set: 2
      amount: 5
      freq: 2
      duration: 20
    others:
      set: 1
      amount: 2
      freq: 2
      duration: 10
```

配置文件 `particles.yml`

```
particles:
  player:   # particles only available for players
    0:  # particle set id
      author: (player uuid)
      name: lovers # a player-defined name
      content:
      - [particle: heart; amount: 3; freq: 20; duration: 10] # list of spawning particles, spawn 3 heart particles per 20 ticks and lasts for 10 ticks
  others:   # particles available for other entities
    1:
      author: (player uuid)
      name: magic-arrow
      content:
      - [particle: end_rod; amount: 2; freq: 2; duration: 10]
    2:
      author: (player uuid)
      name: happy
      content:
      - [particle: note; amount: 1; freq: 5; duration: 20]
      - [particle: spell; amount: 3; freq: 3; duration: 10]
player-settings:
  d763-717a-bb6e-4724-955a-7e23-ef894ada:  # player by uuid
    player: 0  # particle ID
    elytra: 2
    others: 1
```

命令 & 权限组

权限组 `nu.particles.player`

* `/nu particle list [player|elytra|other]` 列出特定分类下的 particle sets，返回

```
[ID] [name] [author]
  - [note, amount 1, freq 5, duration 20]
  - [spell, amount 3, freq 3, duration 10]
```

* `/nu particle set [player|elytra|other] [ID]` 为自己设置特定类型的 particle set

* `/nu particle clear [player|elytra|other]` 清除特定类型的粒子特效设置

权限组 `nu.particles.editor` 可以新建 particle set，编辑或删除自己的 particle set

* `/nu particle create [player|elytra|other] [name]` 新建一个类型的 particle set，返回新建的 set ID
* `/nu particle add [ID] p:[particle name] a:[amount] f:[freq] d:[duration]` 为特定 particle set 添加一个粒子效果，例如 `/nu particle add 1 p:happyVillager a:3 f:20 d:10`
* `/nu particle remove [ID]` 删除一个 particle set

权限组 `nu.particle.admin` 可以编辑或删除任何 particle set
