### ISSUE TITLE
/vote 和 mention

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/NyaaUtils#44]
### Vote

```
/nu vote [vote主题] [选项1] [选项2] <选项3> <选项4> <5> <6> <7> ...
```

响应：

```
/vote [选项ID]
```

配置文件

```
vote:
  enable: true
  timeout: 1200 # ticks
  max_options: 5
```

timeout 后，在聊天频道展示投票结果。

### mention

玩家 ID 被 mention 后，播放声音及提示

```
mention:
  enable: true
  sound:
  - entity.experience_orb.pickup
  - entity.experience_orb.pickup
  - entity.experience_orb.pickup # 连续播放三次 entity.experience_orb.pickup
  notification: ACTIONBAR # TITLE / SUBTITLE / ACTIONBAR / NONE
```
