### ISSUE TITLE
[Feature Request] Extra Backpack

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/NyaaUtils#60]
A feature that adds more backpack space for player.

### Configuration

`config.yml`

```
extra_backpack:
  enable: true
  start_line: 0  # how many chest lines for each player by default
  max_line: 6  # maximum chest lines available for player
  require_nearby_block: NONE  # use block id to require a block nearby to use backpack. NONE for no requirement (can be used anywhere)
  require_nearby_distance: 5 # required distance coverage to block to use backpack, only used when require_nearby_block is not NONE.
```

`backpack.db` stores backpack lines/items (nbt) for each player.

(or use other more optimized way to store items)

### Commands & Permissions

| command | permission | desc |
| --- | --- | --- |
| `/nu bp` | `nu.bp.use` | short hand for open backpack |
| `/nu bp open` | `nu.bp.use` | open backpack |
| `/nu bp open [player]` | `nu.bp.admin` | open other player's backpack |
| `/nu bp set [player] [lines]` | `nu.bp.admin` | set player's available lines |
| `/nu bp add [player] [lines]` | `nu.bp.admin` | add lines to player's backpack |
| `/nu bp del [player] [lines]` | `nu.bp.admin` | remove lines from player's backpack. Items should drop at executor's position |
