### ISSUE TITLE
新增功能：材料修复 用于替代 MythicDrops

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/nyaautils#7]
配置文件 `repair.yml` 内容例如：

```
repairCost:
  WOODEN_PICKAXE:
    material: planks # or use value 5
    fullRepairCost: 2 # how many material is required to fully repair the item, this decide durability amount each material can regain.
    expCost: 1 # exp points (not level) cost on **each consume**
    enchantCostPerLv: 1 # if item is enchanted, each level will require more material and exp to repair. Details below.
    repairLimit: 100 # how many times an item can be fixed, this value is stored in NBT. -1 to disable, in this case no changes will be applied to NBT.
  ELYTRA:
    material: leather
    fullRepairCost: 3
    expCost: 2
    enchantCostPerLv: 2
    repairLimit: -1
(...)
```

管理员命令：

`/nu addrepair [item] [material] [fullRepairCostAmount] [expCostPerConsume] [enchantCostPerLv] [repairTimesLimit]`

权限 `nu.addrepair` 默认为 op

玩家使用：

1. 修复材料放置副手
2. 修复目标物品放置主手
3. 命令 `/nu repair` 消耗一个材料修复，`/nu repair full` 消耗副手材料修复直到修满耐久，或者消耗完副手的材料。耐久消耗不满一个材料修复时，也消耗一个材料和对应经验值并修满耐久。（不会说话了）。`/nu repairinfo` 展示当前主手所持物品的修复信息（无法修复、当前耐久值、需要何种材料修复、消耗一个材料修复所需的经验值和恢复的耐久值、剩余修复可能次数）
4. 材料或经验值不足时提示相应错误

权限 `nu.repair` 默认为玩家

权限 `nu.repairinfo` 默认为玩家

修复后播放铁砧修复的声音。

补充：

举例，配置如下

```
  DIAMOND_PICKAXE:
    material: diamond
    fullRepairCost: 3
    expCost: 2
    enchantCostPerLv: 2
    repairLimit: -1
```

钻石镐的耐久值为 1561，则无附魔的钻石镐每次修复消耗 1 颗钻石和 2 点经验，恢复 `floor(1561/3) = 520` 点耐久。

附魔有耐久 I 和效率 III 的钻石镐（附魔总等级 `1 + 3 = 4`），每次修复消耗 1 颗钻石和 `floor(2 + 2 * 4)` 点经验，并恢复 `floor(1561 / (3 + 2 * 4)) = 141` 点耐久。

`enchantCostPerLv` 可以为 >= 0 的浮点数。
