### ISSUE TITLE
新增功能：自助修改前后缀

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/nyaautils#8]
配置文件内容示例

```
custom-fixes:
  prefix:
    moneyCost: 100
    expCost: 10
    maxlength: 10 # excluding formatting codes 
    disabledFormattingCodes:
    - k # all §k will be trimmed.
    blockedWords:
    - '[Admin]'  # this value ignores all formatting codes, e.g. §f[§cAdmin§f] §r or anything containing '[Admin]' will be blocked as well.
    - somebadwords
    addCommand: 'manuaddv %player% prefix %value%'
    delCommand: 'manudelv %player% prefix'
  suffix:
    maxlength: 10
    moneyCost: 100
    expCost: 10
    disabledFormattingCodes:
    - k
    blockedWords:
    - somebadwords
    addCommand: 'manuaddv %player% suffix %value%'
    delCommand: 'manudelv %player% suffix'
```

玩家命令

* `/nu prefix [value]` 添加前缀
* `/nu resetprefix` 重置前缀
* `/nu suffix [value]` 添加后缀
* `/nu resetsuffix` 重置后缀
* `/nu format` 展示可用的样式代码及效果

权限默认全体玩家

* `nu.prefix`
* `nu.suffix`
* `nu.format`
